USE customer_behavior;

-- Q1. Demographic Revenue: 
-- What is the total revenue generated by male versus female customers? 
select gender, sum(purchase_amount) as total_revenue
from customer
group by gender;

-- Q2. Discount vs. Spend:
-- Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3. Product Ratings: 
-- Which are the top five products with the highest average review rating? 
SELECT item_purchased, round(avg(review_rating),2) as 'Average_Product_Rating' 
FROM customer
group by item_purchased
order by avg(review_rating) desc 
limit 5;

-- Q4. Shipping Impact: 
-- Compare the average purchase amount between standard and express shipping.
select shipping_type, avg(purchase_amount)  
from customer
where shipping_type in ('standard','express')
group by shipping_type;


-- Q5. Subscription Value: 
-- Do subscribed customers spend more? 
select subscription_status, 
count(customer_id) as total_customers,
AVG(purchase_amount) as avg_amount,
SUM(purchase_amount) as total_spend
from customer
group by subscription_status
order by avg_amount, total_spend DESC;

-- Q6. Discount Reliance: 
-- Which five products have the highest percentage of purchases with discounts applied? 
select item_purchased , 
round(100 * SUM(case when discount_applied = 'Yes' then 1 else 0 end) / count(*), 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


-- Q7. Customer Segmentation: 
-- How can we segment customers into 'new', 'returning', and 'loyal' based on their total number of previous purchases?
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'new'
    when previous_purchases between 2 and 10 then 'returning'
    else 'loyal'
    end as customer_segment
from customer
)
select customer_segment, count(*) as 'Num of customer'
from customer_type
group by customer_segment;

-- Q8. Top Products by Category: 
-- What are the top three most purchased products within each category?
with item_counts as (
select category, 
item_purchased,
count(customer_id) as total_order,
ROW_NUMBER() OVER(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_order
from item_counts
where item_rank <= 3;

-- Q9. Subscription Likelihood: 
-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? 
select subscription_status,
count(customer_id) as repeat_buyer
from customer
where previous_purchases >= 5
group by subscription_status ;

-- Q10. Revenue by Age: 
-- What is the total revenue generated by each age group? 
select age_group,
sum(purchase_amount) as total_Revenue
from customer
group by age_group 
order by total_Revenue asc;




